---
#- name: Main playbook
#  hosts: '*'
#  become: yes

 - name: Upgrade all
   ansible.builtin.yum:
    name: '*'
    state: latest
   when: ansible_os_family == "RedHat"

 - name: Update all Debian
   apt:
    update_cache: true
    force_apt_get: yes
    cache_valid_time: 3600
   when: ansible_os_family == "Debian"