---
# defaults file for gitlab
gitlab_edition: "gitlab-ce"
gitlab_repository_installation_script_url: "https://packages.gitlab.com/install/repositories/gitlab/{{ gitlab_edition }}/script.rpm.sh"
gitlab_modules: [ 'curl', 'tzdata', 'perl', 'gnupg2' ]
install_gitlab_root_pass: "ZAQ!xsw2cde3"

# GitLab runner token after install
install_gitlab_runner_token: "98765432109876543210"

# If true, postfix will be installed before GitLab
install_gitlab_postfix_install: true

# If true, postfix service will be enabled permanently
install_gitlab_postfix_enabled: true

# Postfix state after install (started/stopped/reloaded/restarted)
install_gitlab_postfix_state: "started"

# URL on which GitLab will be reachable
install_gitlab_external_url: "http://gitlab.gavva.site"

# Enable internal Let's Encrypt client ("true"/"false")
# Must be "false" for 'http' URL or
# when you have own LE client
# It's string, not bool!
# And lowercase only!
install_gitlab_le_enabled: "false"
proxy_internal_ip: "192.168.101.5"
tf_monitoring_server_ip: "192.168.101.5"