---
- name: Create the replication users
  mysql_user:
    name: "{{ item.name }}"
    host: "%"
    password : "{{ item.pass|default('verystrong') }}"
    priv: "*.*:REPLICATION SLAVE,REPLICATION CLIENT"
    state: present
  with_items:
    - "{{ mysql_repl_user }}"
  when:
     - mysql_replication_role == 'master'
- name: Check slave replication status.
  mysql_replication:
    mode: getreplica
  ignore_errors: true
  register: slave
  when:
    - mysql_replication_role == 'slave'
    - (mysql_replication_master | length) > 0

- name: Check master replication status.
  mysql_replication: mode=getprimary
  delegate_to: "{{ mysql_replication_master }}"
  register: master
  when:
    - mysql_replication_role == 'slave'

- name: Configure replication on the slave.
  mysql_replication:
    mode: changeprimary
    master_host: "{{ mysql_replication_master }}"
    master_user: "{{ mysql_repl_user[0].name }}"
    master_password: "{{ mysql_repl_user[0].pass }}"
    master_log_file: "{{ master.File }}"
    master_log_pos: "{{ master.Position }}"
  ignore_errors: yes
  when:
    -  mysql_replication_role == 'slave'
- name: Start replication.
  mysql_replication: mode=startreplica
  when:
    - mysql_replication_role == 'slave'
