---
- name: Задаем email
  set_fact:
    letsencrypt_email: info@{{ virtual_domain }}

- name: Check if certificate already exists
  stat:
    path: "/etc/letsencrypt/live/{{ virtual_domain }}/cert.pem"
  register: letsencrypt_cert

- name: Generating certificate
  shell: >
    certbot certonly --nginx --email '{{ letsencrypt_email }}'
    --agree-tos --no-eff-email -d '{{ virtual_domain }}'
    -d 'www.{{ virtual_domain }}' -d 'gitlab.{{ virtual_domain }}'
    -d 'grafana.{{ virtual_domain }}' -d 'prometheus.{{ virtual_domain }}'
    -d 'alertmanager.{{ virtual_domain }}'
    {% if letsencrypt_staging %} --staging {% endif %}
  when: not letsencrypt_cert.stat.exists

- name: add to cron
  cron:
    name: Certbot automatic renewal
    job: "certbot renew"
    month: "*/2"