---
# defaults file for mysql
mysql_port: 3306
mysql_bind_address: "0.0.0.0"
mysql_root_db_pass: secret
mysql_db:
  - name: wordpress
    replicate: yes
    collation: utf8_general_ci
    encoding: utf8
mysql_users:
  - name: wordpress
    pass: wordpress
    priv: "*.*:ALL"
mysql_repl_user:
  - name: repl
    pass: verystrong
mysql_repl_role: master
mysql_db_id: 7
mysql_sql_mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
mysql_add_engine: false
mysql_engines: []
mysql_replication_master: db01.gavva.site