---
# defaults file for grafana

version: "9.0.4"

grafana_admin_password: "P@ssW0rd"

grafana_datasources: 
  - name: "Prometheus"
    type: "prometheus"
    access: "proxy"
    url: "http://localhost:9090"
    isDefault: true

grafana_dashboards: 
  - dashboard_id: '3662'
    revision_id: '2'
    datasource: 'Prometheus'
  - dashboard_id: '1860'
    revision_id: '27'
    datasource: 'Prometheus'
  - dashboard_id: '9578'
    revision_id: '4'
    datasource: 'Prometheus'
  - dashboard_id: '9628'
    revision_id: '7'
    datasource: 'Prometheus'

grafana_data_dir: "/var/lib/grafana"
grafana_dashboards_dir: "dashboards"
grafana_provisioning_synced: false